In [1]:
import numpy as np

In [16]:
def get_cov(X):
    N = X.shape[0]
    M = X.shape[1]
    cov = np.zeros(shape=(N, M))
    X = X - np.mean(X, axis=1)
    for i in range(N):
        cov[]
        
print(get_cov(X))

In [13]:
X = np.array([[1, 2, 4, 5], [2, 4, 5, 1], [2, 5, 6, 1], [1, 0, 5, 3], [2, 4, 2, 1]])
print(X.shape)
print(np.cov(X))

print(get_cov(X))

(5, 4)
[[ 3.33333333 -0.33333333 -0.33333333  3.         -1.33333333]
 [-0.33333333  3.33333333  4.33333333  1.          1.33333333]
 [-0.33333333  4.33333333  5.66666667  1.16666667  1.83333333]
 [ 3.          1.          1.16666667  4.91666667 -1.75      ]
 [-1.33333333  1.33333333  1.83333333 -1.75        1.58333333]]


ValueError: operands could not be broadcast together with shapes (5,4) (5,) 