In [26]:
# PACKAGE: DO NOT EDIT THIS CELL
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
%matplotlib inline

In [44]:
def get_projection(B, X):
    print("Shape B = ", B.shape)
    print("Shape X = ", X.shape)
    
    btb = B.T @ B
    print("btb = ", btb)
    lamda = np.linalg.inv(btb) @ B.T @ X 
    projection_matrix = B @ np.linalg.inv(btb) @ B.T
    pie_u_x = B @ lamda 
    
    print("projection matrix: ", projection_matrix, ", rank = ", np.linalg.matrix_rank(projection_matrix))
    print("lamda = ", lamda)
    print("projected point: ", pie_u_x)

    return pie_u_x

X = np.array([12, 0, 0])
B = np.array([[1, 0],
              [1, 1],
              [1, 2]])

print(get_projection(B, X))


Shape B =  (3, 2)
Shape X =  (3,)
btb =  [[3 3]
 [3 5]]
projection matrix:  [[ 0.83333333  0.33333333 -0.16666667]
 [ 0.33333333  0.33333333  0.33333333]
 [-0.16666667  0.33333333  0.83333333]] , rank =  2
lamda =  [10. -6.]
projected point:  [10.  4. -2.]
[10.  4. -2.]


In [49]:
# GRADED FUNCTION: DO NOT EDIT THIS LINE
def projection_matrix_general(B):
    """Compute the projection matrix onto the space spanned by the columns of `B`
    Args:
        B: ndarray of dimension (D, M), the basis for the subspace
    
    Returns:
        P: the projection matrix
    """
    projection_matrix = B @ np.linalg.inv(B.T @ B) @ B.T
    print(projection_matrix.shape)
    return projection_matrix


(3, 3)


array([[ 0.83333333,  0.33333333, -0.16666667],
       [ 0.33333333,  0.33333333,  0.33333333],
       [-0.16666667,  0.33333333,  0.83333333]])

In [56]:
# GRADED FUNCTION: DO NOT EDIT THIS LINE
def project_general(x, B):
    """Compute the projection matrix onto the space spanned by the columns of `B`
    Args:
        x: ndarray of dimension (D, 1), the vector to be projected
        B: ndarray of dimension (D, M), the basis for the subspace
    
    Returns:
        p: projection of x onto the subspac spanned by the columns of B; size (D, 1)
    """
    return projection_matrix_general(B) @ x

# Projects a vector in 3d space to a 2d space using a basis matrix where z dimension is 0 for both the basis vectors.
B = np.array([[1, 0],
              [0, 1],
              [0, 0]])
X = np.array([5, 5, 5])
project_general(X, B)

(3, 3)


array([5., 5., 0.])